# Generated by Django 4.2.13 on 2024-06-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableextractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extracted_json_txt',
            new_name='extracted_table_txt',
        ),
    ]
